### PR TITLE
Update barbs and color table label when units change

### PR DESCRIPTION
**Pull request by tommyjasmin**
Guys - this addresses bugs IDV user HP Roesli found, documented in McV inquiries 1911 and 1925:

http://mcidas.ssec.wisc.edu/inquiry-v/

When changing units. the Wind Barb colors should update appropriately as well as the color table 
unit label.  NOTE: these inquiries have not passed testing in McV yet, you may want to wait until 
Bob and crew have passed these before accepting the Pull Request.

### CODE REVIEW

**Comment by mhiley** [comment]
@tommyjasmin you'll want to incorporate commit https://github.com/mcidasv/mcidasv/commit/221779a324651778c69e4a7fb7bd9631de198ec8 into this pull request once inq. 1911 passes testing.

**Comment by tommyjasmin** [comment]
Thanks Mike, I just brought it in now...

**Comment by mhiley** [comment]
@tommyjasmin here's another commit for this PR, if Bob gives the OK:

https://github.com/mcidasv/mcidasv/commit/81b2628c576d0d2482dba66dcc8a8d0b7eee1556

**Comment by yuanho** [comment]
need more tests

**Pull request merged**
